var searchData=
[
  ['_5f_5farm_5f2d_5fcolor_5ffast_5frgb_5ft_0',['__arm_2d_color_fast_rgb_t',['../group__gConversion.html#union____arm__2d__color__fast__rgb__t',1,'']]],
  ['_5f_5farm_5f2d_5fcolor_5ffast_5frgb_5ft_2e_5f_5funnamed92_5f_5f_1',['__arm_2d_color_fast_rgb_t.__unnamed92__',['../group__gConversion.html#struct____arm__2d__color__fast__rgb__t_8____unnamed92____',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2',['__arm_2d_op_info_t',['../group__gKernel.html#union____arm__2d__op__info__t',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_3',['__arm_2d_op_info_t.Info',['../group__gKernel.html#struct____arm__2d__op__info__t_8Info',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2elowlevelinterfaceindex_4',['__arm_2d_op_info_t.Info.LowLevelInterfaceIndex',['../group__gKernel.html#union____arm__2d__op__info__t_8Info_8LowLevelInterfaceIndex',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2elowlevelinterfaceindex_2e_5f_5funnamed30_5f_5f_5',['__arm_2d_op_info_t.Info.LowLevelInterfaceIndex.__unnamed30__',['../group__gKernel.html#struct____arm__2d__op__info__t_8Info_8LowLevelInterfaceIndex_8____unnamed30____',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2elowlevelinterfaceindex_2e_5f_5funnamed32_5f_5f_6',['__arm_2d_op_info_t.Info.LowLevelInterfaceIndex.__unnamed32__',['../group__gKernel.html#struct____arm__2d__op__info__t_8Info_8LowLevelInterfaceIndex_8____unnamed32____',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2elowlevelinterfaceindex_2e_5f_5funnamed34_5f_5f_7',['__arm_2d_op_info_t.Info.LowLevelInterfaceIndex.__unnamed34__',['../group__gKernel.html#struct____arm__2d__op__info__t_8Info_8LowLevelInterfaceIndex_8____unnamed34____',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2elowlevelio_8',['__arm_2d_op_info_t.Info.LowLevelIO',['../group__gKernel.html#union____arm__2d__op__info__t_8Info_8LowLevelIO',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2elowlevelio_2e_5f_5funnamed36_5f_5f_9',['__arm_2d_op_info_t.Info.LowLevelIO.__unnamed36__',['../group__gKernel.html#struct____arm__2d__op__info__t_8Info_8LowLevelIO_8____unnamed36____',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2elowlevelio_2e_5f_5funnamed38_5f_5f_10',['__arm_2d_op_info_t.Info.LowLevelIO.__unnamed38__',['../group__gKernel.html#struct____arm__2d__op__info__t_8Info_8LowLevelIO_8____unnamed38____',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2elowlevelio_2e_5f_5funnamed40_5f_5f_11',['__arm_2d_op_info_t.Info.LowLevelIO.__unnamed40__',['../group__gKernel.html#struct____arm__2d__op__info__t_8Info_8LowLevelIO_8____unnamed40____',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2eparam_12',['__arm_2d_op_info_t.Info.Param',['../group__gKernel.html#union____arm__2d__op__info__t_8Info_8Param',1,'']]],
  ['_5f_5farm_5f2d_5fop_5finfo_5ft_2einfo_2eparam_2e_5f_5funnamed28_5f_5f_13',['__arm_2d_op_info_t.Info.Param.__unnamed28__',['../group__gKernel.html#struct____arm__2d__op__info__t_8Info_8Param_8____unnamed28____',1,'']]],
  ['_5f_5farm_5f2d_5ftransform_5finfo_5ft_14',['__arm_2d_transform_info_t',['../group__gTransform.html#struct____arm__2d__transform__info__t',1,'']]],
  ['_5f_5farm_5f2d_5ftransform_5finfo_5ft_2e_5f_5funnamed63_5f_5f_15',['__arm_2d_transform_info_t.__unnamed63__',['../group__gTransform.html#struct____arm__2d__transform__info__t_8____unnamed63____',1,'']]],
  ['_5f_5farm_5f2d_5ftransform_5finfo_5ft_2e_5f_5funnamed63_5f_5f_2etarget_16',['__arm_2d_transform_info_t.__unnamed63__.Target',['../group__gTransform.html#struct____arm__2d__transform__info__t_8____unnamed63_____8Target',1,'']]],
  ['_5f_5farm_5f2d_5ftransform_5finfo_5ft_2emask_17',['__arm_2d_transform_info_t.Mask',['../group__gTransform.html#union____arm__2d__transform__info__t_8Mask',1,'']]],
  ['_5f_5farm_5fslist_5fnode_5ft_18',['__arm_slist_node_t',['../group__gKernel.html#struct____arm__slist__node__t',1,'']]]
];
