#ifndef ARM_2D_FTOPTION_H_
#define ARM_2D_FTOPTION_H_

#include <freetype/config/ftoption.h>

#define FT2_BUILD_LIBRARY

#undef  FT_CONFIG_OPTION_USE_MODULE_ERRORS

#undef  FT_CONFIG_OPTION_USE_ZLIB
#undef  FT_CONFIG_OPTION_SYSTEM_ZLIB
#undef  FT_CONFIG_OPTION_USE_BZIP2
#undef  FT_CONFIG_OPTION_USE_LZMA
#undef  FT_CONFIG_OPTION_USE_PNG
#define FT_CONFIG_OPTION_SMALL_FOOTPRINT
#define FT_CONFIG_OPTION_NO_STDERR
#undef  FT_CONFIG_OPTION_PIC


#undef  TT_CONFIG_OPTION_SUBPIXEL_HINTING
#undef  FT_CONFIG_OPTION_SUBPIXEL_RENDERING
#undef  TT_CONFIG_OPTION_EMBEDDED_BITMAPS

#undef  FT_DEBUG_LEVEL_TRACE
#undef  FT_DEBUG_LEVEL_ERROR
#undef  FT_DEBUG_AUTOFIT
#undef  FT_DEBUG_MEMORY
#undef  TT_CONFIG_OPTION_GX_VAR_SUPPORT

#define AF_CONFIG_OPTION_CJK

#endif /* ARM_2D_FTOPTION_H_ */