#ifndef FTOPTION_H_
#define FTOPTION_H_

#undef  FT_CONFIG_OPTION_SYSTEM_ZLIB
#undef  FT_CONFIG_OPTION_USE_BZIP2
#undef  FT_CONFIG_OPTION_USE_LZMA
#undef  FT_CONFIG_OPTION_USE_PNG
#undef  FT_CONFIG_OPTION_USE_HARFBUZZ
#define FT_CONFIG_OPTION_SMALL_FOOTPRINT
#define FT_CONFIG_OPTION_NO_STDERR
#undef  FT_CONFIG_OPTION_PIC

#undef  TT_CONFIG_OPTION_SUBPIXEL_HINTING
// #undef FT_CONFIG_OPTION_SUBPIXEL_RENDERING

#undef  TT_CONFIG_OPTION_EMBEDDED_BITMAPS
#define AF_CONFIG_OPTION_CJK


#include <ft2build.h>
#endif /* FTOPTION_H_ */