name: Run test on Arm Virtual Hardware

on:
  workflow_dispatch:
  push:
    branches: [ main, developing ]
  pull_request:
    branches: [ main, developing ]

env:
  # Enable the next two lines if you are using IAM User and you added them in the repo's secret.
  # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_S3_BUCKET_NAME: ${{ vars.AWS_S3_BUCKET_NAME }}
  AWS_IAM_PROFILE: ${{ vars.AWS_IAM_PROFILE }}
  AWS_SECURITY_GROUP_ID: ${{ vars.AWS_SECURITY_GROUP_ID }}
  AWS_SUBNET_ID: ${{ vars.AWS_SUBNET_ID }}

jobs:
  ci_test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Python requirements
      run: |
        pip install -U -r test/requirements.txt

    - uses: ammaraskar/gcc-problem-matcher@master

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: ${{ vars.AWS_ASSUME_ROLE }}
        aws-region: ${{ vars.AWS_DEFAULT_REGION }}

    - name: Run tests
      id: avh
      run: |
        avhclient -b aws execute --specfile test/avh.yml

    - name: Archive results
      uses: actions/upload-artifact@v3
      with:
        name: results
        path: |
          test/arm2d_*.zip
        retention-days: 1
        if-no-files-found: error
      if: always()
