/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'pico_template' 
 * Target:  'OLED_12864' 
 */

#ifndef PRE_INCLUDE_DEVICE_PICO_SDK_H
#define PRE_INCLUDE_DEVICE_PICO_SDK_H

/* RaspberryPi::Device:Pico SDK@1.5.1 */
#define LIB_CMSIS_CORE                  1
            #define PICO_CMSIS_RENAME_EXCEPTIONS    1

#endif /* PRE_INCLUDE_DEVICE_PICO_SDK_H */
